[package]
name = "tantivy_demo"
version = "0.1.0"
edition = "2021"
default-run = "tantivy_demo"

[[bin]]
name = "search_tests"
path = "src/search_tests.rs"

[[bin]]
name = "facet_mapping"
path = "src/facet_mapping.rs"

[[bin]]
name = "lancedb_demo"
path = "src/lancedb_demo.rs"

[dependencies]
tantivy = "0.24"
walkdir = "2.5"
rand = "0.8"
rand_chacha = "0.3"
bytemuck = "1.16"
twox-hash = "1.6"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"