# Development Configuration
# Optimized for fast iteration and testing

[data]
# Data directory structure
raw_txt_dir = "../dev_data/raw"
tantivy_index_dir = "../dev_data/indexes/tantivy"
lancedb_index_dir = "../dev_data/indexes/lancedb"

[search]
# Search configuration - smaller limits for dev
default_limit = 3
max_limit = 20
fuzzy_max_distance = 2

[facets]
# Facet configuration
categories = ["tech/math", "tech/it", "lit/fiction", "lit/romcom"]

[embedding]
# Embedding configuration - same as prod for consistency
dimension = 1536  # OpenAI text-embedding-3-small
model = "text-embedding-3-small"

[lancedb]
# LanceDB vector index configuration - DEV OPTIMIZED
# Much smaller partitions for faster dev iteration
num_partitions = 64         # ~390 vectors per partition (25K vectors)
num_sub_vectors = 96        # 1536/96=16 sub-vectors (SIMD optimized)
metric = "cosine"           # Cosine similarity for text embeddings

[lancedb_search]
# Search parameters - DEV OPTIMIZED
# Smaller probes and refine factor for faster dev testing
nprobes = 4                 # 6% of partitions for good recall
refine_factor = 10          # 10x over-retrieval (vs 40x in prod)
default_limit = 3           # Smaller result set for dev
max_limit = 20              # Smaller max for dev

[server]
# Server configuration - dev settings
host = "127.0.0.1"
port = 8081  # Different port to avoid conflicts

[dev]
# Development-specific settings
enable_debug_logging = true
fast_indexing = true
skip_expensive_operations = true
test_data_size = 1000  # Limit test data size
