[package]
name = "localdb-hybrid"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
localdb-core = { path = "../localdb-core" }
localdb-text = { path = "../localdb-text" }
localdb-vector = { path = "../localdb-vector" }
localdb-embed = { path = "../localdb-embed" }
