[package]
name = "localdb-text"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
walkdir = { workspace = true }
tantivy = { workspace = true }
localdb-core = { path = "../localdb-core" }
