[package]
name = "localdb-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
figment = { version = "0.10", features = ["env", "toml"] }
walkdir = "2.5"

[dev-dependencies]
tempfile = "3.0"
