# Production environment configuration
environment: prod

# Data paths (relative to project root)
data:
  raw_dir: "../data/raw"
  txt_dir: "../data/txt"
  
# PDF processing settings
pdf:
  # Text extraction method: "pymupdf", "pdfplumber", "pypdf2"
  extractor: "pymupdf"
  # Minimum text length to keep
  min_text_length: 100
  # Maximum line length before splitting
  max_line_length: 2000

# Text cleaning settings
text_cleaning:
  # Remove empty lines
  remove_empty_lines: true
  # Remove lines with only whitespace
  remove_whitespace_only: true
  # Remove very short lines (less than N characters)
  min_line_length: 20
  # Preserve paragraph breaks
  preserve_paragraphs: true
  # Normalize whitespace
  normalize_whitespace: true

# Logging
logging:
  level: "WARNING"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"