# Test environment configuration
environment: test

# Data paths (relative to project root)
data:
  raw_dir: "../test_data/raw"
  txt_dir: "../test_data/txt"
  
# File processing settings
pdf:
  # Text extraction method: "pymupdf" (fast), "pdfplumber", "pypdf2", "unstructured" (slower)
  extractor: "pymupdf"
  # Minimum text length to keep
  min_text_length: 10
  # Maximum line length before splitting
  max_line_length: 1000

# Text cleaning settings
text_cleaning:
  # Remove empty lines
  remove_empty_lines: true
  # Remove lines with only whitespace
  remove_whitespace_only: true
  # Remove very short lines (less than N characters)
  min_line_length: 5
  # Preserve paragraph breaks
  preserve_paragraphs: true
  # Normalize whitespace
  normalize_whitespace: true
  # English-only text processing (removes non-ASCII chars)
  english_only: true
  # Convert to lowercase during cleaning
  lowercase: false

# Logging
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
